version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USERNAME: postgres
      - POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/ver/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
 